language: node_js
node_js:
  - "7.9.0"
install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
  
script:
  - npm run bundle
  - node_modules/karma/bin/karma start karma.conf.js --single-run --browsers Firefox

